#!/bin/bash

## link settings files from the repo to this computer
## Usage:
## ./import
#    imports all files from "src"
## ./import list of files
#    imports files "list", "of" and "files", if they exist in "src"

# destination for links
dest=~

# path to repo from ${dest}
repo="config"

# source directory for linked files, relative to ${repo}
target="src"

# files to be linked
files="$(
    if [ "$#" -eq "0" ] ;
    then
        ls -1 "${target}" # all the files in source directory
    else
        IFS=$'\n'; echo "$*" # all the files listed in the command line args
    fi
        )"

# don't do anything if there's nothing to do
if [ "${files}" == "" ];
then
    echo "no files to link, exiting"
else
    # files which would be overwritten
    overwrites="$(
        echo "${files}"| # for each file
            while IFS='' read file;
            do
                ls -1a "${dest}" | grep "^.${file}$" # file exists in destination directory, as a hidden file
            done
                )"
    if [ "${overwrites}" != "" ];
    then
        echo "This action will overwrite the following files:"
        echo "${overwrites}"|
            sed "s:^:${dest}/:" # format it nicely with the path
    fi

    # confirm that this is fine
    echo -n "Are you sure? (y/N): "
    read confirm
    [ -t 0 ] || echo # if not open in a terminal, add the implicit newline from read
    if echo "${confirm}"|grep -E "[Yy]+([Ee]+[Ss]+)*">/dev/null;
    then # they tried to say yes
        echo "${files}"| # for each file
            while IFS='' read file; 
            do
                if [ -e "${target}/${file}" ];
                then # target file exists
                    ln -sfvT "${repo}/${target}/${file}" "${dest}/.${file}" # create the symbolic link, overwriting, verbose
                else # file doesn't exist
                    echo "Warning: cannot create link to nonexistent file \"${target}/${file}\"" # don't create bad links
                fi
            done
    else # they said something else; assume no
        echo "aborting" # let the user know nothing happened
        exit 1
    fi
fi
