#!/bin/bash

## link settings files from the repository to this computer
#  linked files will have '.' prepended to their filename
## Usage:
## ./link
#    links all files from "src"
## ./link list of files
#    links files "list", "of" and "files", if they exist in "src"
#    cannot handle paths to files
#    ignores leading '.'s in filenames, as no source files may be hidden

# destination for links
dest="$HOME"

# path to repo from ${dest}
repo="config"

# source directory for linked files, relative to ${repo}
target="src"

# files to be linked
files="$(
    if [ "$#" -le 0 ] ; # no arguments
    then
        ls -1 "${target}" # all the files in source directory
    else
        IFS=$'\n'; echo "$*" # all the files listed in the command line args
    fi
        )"

# don't do anything if there's nothing to do
if [ -z "${files}" ];
then
    echo "no files to link, exiting"
else
    # files which would be overwritten
    overwrites="$(
        echo "${files}"| # for each file
            while IFS='' read file;
            do
                ls -1a "${dest}" | grep "^.${file}$" # file exists in destination directory, as a hidden file
            done
                )"
    if [ -n "${overwrites}" ];
    then
        echo "This action will overwrite the following files:"
        echo "${overwrites}"|
            sed "s:^:${dest}/:" # format it nicely with the path
    fi

    echo -n "Are you sure? (y/N): "
    read confirm
    if ! [ -t 0 ] ;
    then # open in a pipe
        # simulate user input
        echo "${confirm}"
    fi
    if echo "${confirm}"|grep -Eq "[Yy]+([Ee]+[Ss]+)*" ;
    then # they tried to say yes
        echo "${files}"| # for each file
            while IFS='' read file; 
            do
                if [ -e "${target}/${file}" ];
                then # target file exists
                    rm -rf "${dest}/.${file}" &&
                    ln -sfvT "${repo}/${target}/${file}" "${dest}/.${file}" # create the symbolic link, overwriting, verbose
                else # file doesn't exist
                    echo "Warning: cannot create link to nonexistent file \"${target}/${file}\"" # don't create bad links
                fi
            done
    else # they said something else; assume no
        echo "aborting" # let the user know nothing happened
        exit 1
    fi
fi
